# Generated by Django 5.2.12 on 2026-03-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalprofile',
            name='medications',
        ),
    ]
