# Generated by Django 5.2.12 on 2026-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_profile', '0003_medicalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalprofile',
            name='emergency_contact',
            field=models.CharField(max_length=15),
        ),
    ]
