# Generated by Django 5.2.12 on 2026-03-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
